# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_captura_datos.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interfaz_captura_datos(object):
    def setupUi(self, interfaz_captura_datos):
        interfaz_captura_datos.setObjectName("interfaz_captura_datos")
        interfaz_captura_datos.resize(801, 361)
        self.centralwidget = QtWidgets.QWidget(interfaz_captura_datos)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 371, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cantidad_limitada = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cantidad_limitada.setObjectName("cantidad_limitada")
        self.verticalLayout.addWidget(self.cantidad_limitada)
        self.tiempo_real = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.tiempo_real.setObjectName("tiempo_real")
        self.verticalLayout.addWidget(self.tiempo_real)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 9, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphWidget = PlotWidget(self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(410, 30, 371, 261))
        self.graphWidget.setObjectName("graphWidget")
        interfaz_captura_datos.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(interfaz_captura_datos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        interfaz_captura_datos.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(interfaz_captura_datos)
        self.statusbar.setObjectName("statusbar")
        interfaz_captura_datos.setStatusBar(self.statusbar)

        self.retranslateUi(interfaz_captura_datos)
        QtCore.QMetaObject.connectSlotsByName(interfaz_captura_datos)

    def retranslateUi(self, interfaz_captura_datos):
        _translate = QtCore.QCoreApplication.translate
        interfaz_captura_datos.setWindowTitle(_translate("interfaz_captura_datos", "MainWindow"))
        self.cantidad_limitada.setText(_translate("interfaz_captura_datos", "Escoger la cantidad de datos que deseas capturar"))
        self.tiempo_real.setText(_translate("interfaz_captura_datos", "Decidir hasta que momento se van a capturar datos durante la ejecución"))
        self.label.setText(_translate("interfaz_captura_datos", "Selecciona el método de captura de datos que deseas realizar:"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interfaz_captura_datos = QtWidgets.QMainWindow()
    ui = Ui_interfaz_captura_datos()
    ui.setupUi(interfaz_captura_datos)
    interfaz_captura_datos.show()
    sys.exit(app.exec_())
